### ISSUE TITLE
Suggestion: Multi-File support

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/cli#5]
~~~
/Volumes/Scyndi/GameJolt/cli/gjpush --token="TOKEN" --game=GAME --package=PACKAGE -r=0.0.0-test2 *.7z
Too many arguments! Maybe you need to escape the file name if it contains spaces?
~~~

I guess the "too many arguments" is thrown as Unix now automatically adds all files it can find suffixed with .7z but perhaps making this possible in one go, should be nice, since after all I am a Mac user myself, but if I can upload both the Mac version and the Windows version (and perhaps also the Linux version) in one go it would be a great improvement.

**Comment by YLivay** [comment]
Interesting suggestion,  bu I think that's something that should be handled by unix.
if you're depending on mac to expand *.7z you can also depend on it to expand them into separate gjpush commands (list | xargs). not something that should be built into the cli.

**Comment by Tricky1975** [comment]
Maybe or you can do the same trick unix itself does
If you type rm *.zip in unix rm will actually execute itself again with each file separately, like this:
I type rm *.zip and unix does rm file1.zip;rm file2.zip;rm file3.zip
Looks amateur, but it is how unix does it itself… Of course, a little tool to “cheat” on this to add to gjpush is easily written XD
