### ISSUE TITLE
Suggestion: Binary diffing to push new builds

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/cli#7]
Now I've been pushing my game a few times with both gjpush and with butler (the itch.io equivalent) and butler didn't even need half the time gjpush needed, but butler 'cheats' a little. Butler compares the newest push with the second-newest push and only uploads the data that has actually been changed, saving tons of time and bandwidth in the process. Not all countries have unlimited bandwidth (yet), so it is something to consider. I guess the hard part lies in the fact that Game Jolt has a more complicated set up with packages and releases which itch.io does not (when the filename/directory is the same it will start comparing and replacing automatically), still if there are some possibilities here, a lot of people could be grateful :)
I also wonder how Butler really manages to do this, since my game is basically one big packed file containing all the data with only a few extra files for executables and libraries, but still it appears to be able to do this based on the upload times, and also claiming that only 2% new data was changed, and since I use a packing system I designed myself, I deem it unlikely it knows how my package system works, but hey, I've seen crazier things.

If this is undoable in the way GJ is set up, we can still scrap this idea, but maybe we do need to give it some consideration. 😉

**Comment by YLivay** [comment]
I don't know how Butler does it, but for us we'll be supporting the goold ol' time proven rsync for uploading, as well as uploading from a URL :)

I didn't want to make issues for features we have planned farther along but I guess why not!
Consider this suggestion accepted!

**Comment by Tricky1975** [comment]
"I didn't want to make issues for features we have planned farther along but I guess why not!"

I figured that as long as the cli is only available to me and another select group of testers, it would be better to use this issue tracker for suggestions rather than the gj-improve forum, as I think that would only cause confusion. However once the cli tool is publicly usable for everybody I guess the gj-improve forum can be used for the cli as well... ;)
